application:
  description: Sample description
  version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /
  shutdown: "graceful"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 123456
    initialize: true
  jackson:
    fail-on-unknown-properties: false
  logging:
    level:
      root: info
    file:
      path: logs
      max-size: 10KB
      max-history: 7