application:
  description: Sample description
  version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /
  shutdown: "graceful"

spring:
  jackson:
    fail-on-unknown-properties: false
  cloud:
    function:
      definition: SampleS3LambdaEvent
  logging:
    level:
      root: info
    file:
      path: logs
      max-size: 10KB
      max-history: 7